---
- name: Welcome Rulebook
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 1
  rules:
    - name: Say Hello
      condition: event.i == 0
      action:
        debug:
          msg: "EDA is working!"